version: '3.8'
services:
  mongo:
    image: mongo:8.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  solr:
    image: solr:9.9.0
    ports:
      - "8983:8983"
    command: -c "solr-precreate products"
    volumes:
      - solr-data:/var/solr/data