version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    command: -c "solr-precreate products"
    volumes:
      - solr-data:/var/solr/data
